# Generated by Django 3.1.7 on 2021-04-29 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='price',
            new_name='purchase_price',
        ),
    ]
